# Change these first
owner: Gavin132 # Your GitHub organization or username, where this repository lives
repo: status.ankerd.org # The name of this repository

sites:
  - name: ankerd.nl - Main website
    url: https://ankerd.nl
  - name: pws.ankerd.nl - A Mandelbrot simulation site
    url: https://pws.ankerd.nl
  - name: soc.ankerd.nl - Scheikunde moppen
    url: https://soc.ankerd.nl
  - name: con.ankerd.org - Convention management application
    url: https://con.ankerd.org
  - name: dev.ankerd.org - Convention management application BETA
    url: https://dev.ankerd.org
  - name: cdn.ankerd.org - CDN
    url: https://cdn.ankerd.org/story-photos/uploads/b7509915fe6347e3948d583195fef248.jpg
  - name: nextcloud.ankerd.org - Nextcloud
    url: https://nextcloud.ankerd.org
  - name: wordpress.ankerd.org - Portfolio site
    url: https://wordpress.ankerd.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ankerd.org
  # baseUrl: /your-repo-name
  logoUrl: https://media.discordapp.net/attachments/465068365472464906/1550523197965734009/ankerdmascotteankerdlogountitledcentre.png?ex=6aaea4c1&is=6aad5341&hm=0c5433e686468ef52eb293e6cc1d4dc03c2cd60a2dc6c694e0ee0e4d7fc9a1b2&=&format=webp&quality=lossless&width=1280&height=1280
  name: status.ankerd.org
  introTitle: "Uptime monitor for all ankerd projects."
  introMessage: All ankerd projects
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: |
    /* line + space after the 3rd site */
    article:nth-of-type(3) {
      margin-bottom: 2rem;
      padding-bottom: 1.5rem;
      padding-top: 1.5rem;
      border-bottom: 2px solid #ddd;
    }
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
